export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const ITEmployee = ["Amged", "Arsany", "Anton"];

export const branches = [
  "Mallawi",
  "Minya",
  "Maghagha",
  "El-Fashn",
  "Matai",
  "El-Adwa",
  "Beba",
  "Samalout",
  "Bani Mazar",
  "Abu Qurqas",
  "Beni Suef",
  "Samsata",
  "Ihnasia",
  "Nasser",
  "Dairut",
  "El-Qusiya",
  "Asyut",
  "El-Sharafa",
  "Deir Mawas",
  "Abnub",
  "Abshadat",
  "Manfalut",
  "Sandafa",
  "El-Badari",
  "Sahel Selim",
  "Abu Tig",
  "Towa",
  "Bani Ubayd",
  "Abu El-Waqf",
  "Al-Muallimin",
  "Shousha",
  "Helwa",
  "El-Fant",
  "Talt",
  "Saddis",
  "El-Rouda",
  "El-Fath",
  "Sadfa",
  "El-Kharga",
  "Nag Hammadi",
  "Nag Hammadi East",
  "Sohag East",
  "El-Maragha",
  "Naqada",
  "Qus",
  "Tama",
  "Abwan",
  "El-Hawatekah",
  "Monqabad",
  "Sohag",
  "Qena",
  "Farshout",
  "Banha",
  "Tukh",
  "Shubra El-Kheima",
  "Kafr El-Sheikh",
  "El-Riyad",
  "Desouk",
  "Maseer",
  "Qellin",
  "Abu Dunya",
  "El-Hamoul",
  "Sidi Salim",
  "Juhaynah",
  "El-Balina",
  "Girga",
  "Belinsura",
  "Bani Ahmed El-Sharqiya",
  "Imbaba",
  "Dar El-Salam",
  "El-Zaher",
  "Jisr El-Suez",
  "Shubra Masr",
  "El-Marg",
  "Shibin El-Qanater",
  "Tanta",
  "Kom Hamada",
  "Itay El-Barud",
  "El-Rahmaniya",
  "Menia El-Nasr",
  "Belqas",
  "El-Senbellawein",
  "Dekernes",
  "Rashid",
  "Madiyat Rashid",
  "Sadmant",
  "Beni Suef East",
  "Tonsa",
  "Atsa",
  "Helwan",
  "Tarshoub",
  "El-Nawawra",
  "Abu Tisht",
  "Kafr El-Zayat",
  "El-Santa",
  "Samannoud",
  "Sanbu",
  "Tahta",
  "Abu El-Matamir",
  "Botros",
  "El-Mahmoudiya",
  "Damanhur",
  "Shubrakhit",
  "Housh Issa",
  "Kom El-Barka",
  "Matubas",
  "Zefta",
  "El-Wasta",
  "Qalyub",
  "Qatur",
  "Tamiya",
  "Fayoum",
  "Senouris",
  "Aja",
  "El-Shohdah",
  "Faysal",
  "Atfih",
  "El-Ayyat",
  "El-Quturi",
  "Dandil",
  "Hehia",
  "Kafr Sakr",
  "Minya El-Qamh",
  "Abu Kabir",
  "Abu Hammad",
  "Deirab Najm",
  "Faqous",
  "El-Dalangat",
  "Tala",
  "Ashmoun",
  "Giza",
  "El-Munashiya",
  "Bulaq El-Dakrour",
  "Gamyana",
  "Suez",
  "El-Qanater",
];
